### ISSUE TITLE
“aux layers are randomly initialized with orthogonal vectors”

### ISSUE THREAD

**Issue by YoucanBaby** [wallowind/hyper_peft#1]
Thx a lot for your code~!

Do you now have any idea how to better “aux layers are randomly initialized with orthogonal vectors”?

**Comment by wallowind** [comment]
Sorry for the late and perhaps not very helpful reply: no, I haven't thought of a better way.

I'm not sure it's possible because row orthogonality requires linear row independence, which is not fulfilled if the number of columns is less than the number of rows in the matrix (AFAIK).
I would say that column-wise orthogonality in aux A (as happened to be the case in my code) is actually desirable, since it means that we project (factorize) the original weight onto an orthogonal basis, which supposedly gives a good inductive bias for the trainable LoRA weights. But this is already speculation.

In the end, this approach did not give better results than the conventional LoRA for my tasks, and I did not work on it further.
